### ISSUE TITLE
Features/Data availability ETA?

### ISSUE THREAD

**Issue by bradezard131** [ChongQingNoSubway/DGR-MIL#1]
Hi,

Congrats on the ECCV acceptance, well deserved. Also on frontpaging PapersWithCode. Your paper is extremely well presented and very thorough. The experiments are so thorough that I'd really like to build on top of it myself for some things I'm working on, as it is hard to compare so many methods when they all use different splits and preprocessing. 

As such I was wondering when you are aiming to provide the precomputed features? If there's anything I can do to assist in making these available I'd be happy to help.

**Comment by ChongQingNoSubway** [comment]
Thanks very much for your interest in our work. We will soon release pre-computed features for Resnet 18 and Vision Transformer.
For Resnet-50 extracted features, you can find in DFTD-MIL:   https://github.com/hrzhang1123/DTFD-MIL

**Comment by bradezard131** [comment]
The dataset constructors seem to mostly depend on some files `train_official.csv`/`val_official.csv`/`test_official.csv` which don't seem to be part of DTFD-MIL. Would you be able to provide those files or point out where to find them?

**Comment by ChongQingNoSubway** [comment]
I have uploaded the extracted feature and training, and the testing dataset splits CSV files.

**Comment by bradezard131** [comment]
Much appreciated
