### ISSUE TITLE
NSCLC Labels

### ISSUE THREAD

**Issue by lingxitong** [ChongQingNoSubway/DGR-MIL#4]
Hello,Nice work. I have a question.TCGA-NSCLC is a subtyping task for LUAD and LUSC.There is no concept of positive and negative like it in Camelyon-Dataset. So may be the DGR-MIL is more suitable for the normal/tumor task but not the subtyping task.

**Comment by ChongQingNoSubway** [comment]
Thanks for your interest in our work, we had a discussion here  #3, please refer to
